# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-24 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes_on_quotes',
            field=models.ManyToManyField(related_name='quotes_user_liked', to='valid.User'),
        ),
    ]
