# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='messages',
        ),
    ]
