# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0001_initial'),
        ('wall', '0004_auto_20190522_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes_on_c',
            field=models.ManyToManyField(related_name='comments_liked', to='valid.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes_on_m',
            field=models.ManyToManyField(related_name='messages_liked', to='valid.User'),
        ),
    ]
